import React, { useState } from 'react'

function App() {
  const [firstName, setFirstName] = useState('')
  const [msg, setMsg] = useState('')

  const handleSubmit = (e) => {
    e.preventDefault()
    if (!firstName) return
    const corporate_names = [
      '&',
      '.com',
      'Academy',
      'Airlines',
      'Apartments',
      'Apparel',
      'Ashram',
      'Associate',
      'Association',
      'Audit',
      'Autocars',
      'Automobile',
      'Automotive',
      'Ayurveda',
      'Bank',
      'Banks',
      'Bay',
      'Bazar',
      'Beauty',
      'Belief',
      'Bhavan',
      'Biotech',
      'Birla',
      'Bisto',
      'Bliss',
      'Blog',
      'Brahmari',
      'Brothers',
      'Build',
      'Builder',
      'Café',
      'Cafe',
      'Cancer ',
      'Capital',
      'Cargo',
      'Cement',
      'Center',
      'Centre',
      'Chain',
      'Chandh',
      'Chapel',
      'Charitable',
      'Charity',
      'Chit',
      'Christian',
      'Church',
      'Cinema',
      'City',
      'Clothing ',
      'Club',
      'Co',
      'College',
      'Commercial',
      'Communication',
      'Comp',
      'Company',
      'Complex',
      'Concern',
      'Congregation',
      'Congress',
      'Construction',
      'Consult',
      'Consultancy',
      'Corner',
      'Corporation',
      'Cuisine',
      'Cultural',
      'Culture',
      'Dairy',
      'Delights',
      'Design',
      'Designer',
      'Develop',
      'Development',
      'Diamond',
      'Disaster',
      'Dividend',
      'Divine',
      'Dream',
      'E-Commerce',
      'ECommerce',
      'Education',
      'Educational',
      'Empire',
      'Enterprise',
      'Exchange',
      'Export',
      'Express',
      'Facility',
      'Factory',
      'Family',
      'Fellowship',
      'Fencing',
      'Finance',
      'Foods',
      'Foundation',
      'Fresh',
      'Fzc',
      'Games',
      'Gateway',
      'General',
      'Gramin',
      'Grill',
      'Grocery',
      'Group',
      'Health',
      'Holding',
      'Holiday',
      'Holy',
      'Homes',
      'Hope',
      'Hospital',
      'Hotel',
      'Housing',
      'Humanitarian',
      'Ideas',
      'Import',
      'Inc',
      'Indigo',
      'Industries',
      'Infotech',
      'Institute',
      'International',
      'Islamic',
      'Jesus',
      'Jewellers',
      'Karate',
      'Karma',
      'Kenthra',
      'Kitchen',
      'Ksfe',
      'Life',
      'Llc',
      'Loan',
      'Logistics',
      'Ltd',
      'Luxury',
      'Mahal',
      'Maintenance',
      'Majic',
      'Management',
      'Mania',
      'Mart',
      'Masala',
      'Masjid',
      'Mattress',
      'Medical',
      'Merchant',
      'Metals',
      'Minister',
      'Mission',
      'Missionary',
      'Mobile',
      'App',
      'Mosque',
      'Motor',
      'Museum',
      'Muslim',
      'Natural',
      'Oborne',
      'Operative',
      'Organization',
      'Outfits',
      'Outlet',
      'Paint',
      'Palace',
      'Party',
      'Pastor',
      'Pastorate',
      'Payment',
      'Perfect',
      'Pharma',
      'Plates',
      'Political',
      'Poor',
      'Poultry',
      'Power',
      'Priest',
      'Private',
      'Limited',
      'Profit',
      'Project ',
      'Provider',
      'Pvt',
      'Pyar',
      'Rally',
      'Real',
      'Estate',
      'Repairs',
      'Resort',
      'Resorts',
      'Retreats',
      'Saffron',
      'Sales',
      'Salon',
      'Sarees',
      'Sarkar',
      'Scheme',
      'School',
      'Securities',
      'Security',
      'Sensation',
      'Service',
      'Services',
      'Seva',
      'Shipping',
      'Shop',
      'Shopee',
      'Sleep',
      'Snacks',
      'Social',
      'Society',
      'Sole',
      'Solutions',
      'Sons',
      'Spa',
      'Space',
      'Spice',
      'Spoon',
      'Stall',
      'Store',
      'Structure',
      'Studies',
      'Studio',
      'Sutra',
      'Taj',
      'Tandoori',
      'Tax',
      'Teaching',
      'Tech',
      'Technology',
      'The',
      'Tikka',
      'Tour',
      'Tours',
      'Town',
      'Trade',
      'Trader',
      'Trading',
      'Transport',
      'Travel',
      'Travels',
      'Treasure',
      'Trust',
      'University',
      'Ventures',
      'Villas',
      'Visionary',
      'Vlog',
      'Wear',
      'Welfare',
      'Windows',
      'Workshop',
      'Yoga'
    ]
    const block_corporate = (str) => {
      const words = str?.split(/\s+/)
      for (let i = 0; i < words?.length; i++) {
        if (
          corporate_names?.some(
            (v) =>
              v?.toLowerCase()?.replace(/\s/g, '') ==
              words[i]?.toLowerCase()?.replace(/\s/g, '')
          )
        ) {
          setMsg('corporates and charitable institutions are not allowed')
          return
        }
      }
      setMsg('allowed')
    }
    block_corporate(firstName)
  }

  return (
    <>
      <div className="main">
        <p style={{ color: 'red' }}>{msg}</p>
        <form onSubmit={handleSubmit}>
          <div>
            <label>
              First Name:
              <input
                className="inp"
                type="text"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
              />
            </label>
          </div>
          <button className="btn" type="submit">
            Submit
          </button>
        </form>
      </div>
    </>
  )
}

export default App
